Asoul_package="
Nekootan.kfkj
age.of.civilizations2.jakowski.lukasz
brownmonster.app.game.rushrally3
com.AlfaBravo.Combat
com.BlackSaltGames.DREDGE
com.CarXTech.highWay
com.ChillyRoom.DungeonShooter
com.EtherGaming.PocketRogues
com.Flanne.MinutesTillDawn.roguelike.shooting.gp
com.GameCoaster.ProtectDungeon
com.GentleManiac.HorizonWalkerGoogle
com.GlobalSoFunny.Sausage
com.HoYoverse.hkrpgoversea
com.LanPiaoPiao.PlantsVsZombiesRH
com.MOBGames.PoppyMobileChap1
com.ProjectMoon.LimbusCompany
com.RoamingStar.BlueArchive
com.Roboatino.ShogunShowdown
com.ShinyShoe.MonsterTrain.mtap
com.Shooter.ModernWarfront
com.Shooter.ModernWarships
com.Sunborn.SnqxExilium
com.TechTreeGames.TheTower
com.YiMoXuan.XYZJF
com.YoStarEN.Arknights
com.YoStarEN.MahjongSoul
com.YoStarEN.StellaSora
com.YoStarJP.MajSoul
com.YostarJP.BlueArchive
com.ZeroCastleGameStudio.StrikeBusterPrototype
com.ZeroCastleGameStudioINTL.StrikeBusterPrototype
com.actgames.bbee
com.activision.callofduty.shooter
com.activision.callofduty.warzone
com.albiononline
com.aligames.kuang.kybc
com.and.games505.Terraria
com.axlebolt.standoff2
com.bairimeng.dmmdzz
com.bandainamcoent.idolmaster_gakuen
com.bandainamcoent.imas_millionlive_theaterdays
com.bandainamcoent.sao
com.bandainamcoent.shinycolorsprism
com.bandainamcogames.dbzdokkanww
com.bf.sgs.hdexp.bd
com.bhvr.deadbydaylight
com.bilibili.azurlane
com.bilibili.deadcells.mobile
com.bilibili.fatego
com.bilibili.heaven
com.bilibili.priconne
com.bilibili.star.bili
com.bilibili.warmsnow
com.biligamekr.aggp
com.bingkolo.kleins.cn
com.blade.bd
com.blizzard.diablo.immortal
com.blizzard.wtcg.hearthstone
com.bscotch.crashlands2
com.bushiroad.d4dj
com.bushiroad.lovelive.schoolidolfestival2
com.chucklefish.stardewvalley
com.cnvcs.xiangqi
com.crunchyroll.gv.shogunshowdown.game
com.crunchyroll.princessconnectredive
com.denachina.g13002010
com.denchi.vtubestudio
com.dfjz.moba
com.dgames.g15002002
com.digitalextremes.warframemobile
com.dragonli.projectsnow
com.dragonli.projectsnow.lhm
com.dts.freefire
com.dts.freefireth
com.ea.game.pvz2_row
com.ea.games.r3
com.ea.games.r3_row
com.epicgames.fortnite
com.fantablade.icey
com.gaijingames.wtm
com.gameloft.android.ANMP.GloftA9HM
com.garena.game.codm
com.garena.game.df
com.garena.game.kgtw
com.garena.game.kgvn
com.garena.game.nfsm
com.gbits.funnyfighter.android.overseas
com.gryphline.endfield.gp
com.gryphline.exastris.gp
com.guigugame.guigubahuang
com.guyou.deadstrike
com.h73.jhqyna
com.halo.windf.hero
com.heavenburnsred
com.hermes.h1game
com.hermes.j1game
com.hermes.mk
com.hermes.mk.asia
com.herogame.gplay.punishing.grayraven.tw
com.hg.lbw
com.hottapkgs.hotta
com.humo.yqqsqz.yw
com.hypergryph.arknights
com.hypergryph.endfield
com.hypergryph.exastris
com.idreamsky.klbqm
com.ignm.raspberrymash.jp
com.ilongyuan.cytus2
com.ilongyuan.implosion
com.infoldgames.infinitynikkien
com.jacksparrow.jpmajiang
com.je.skgame
com.jumpw.mobile300
com.kiloo.subwaysurf.gw
com.komoe.kmumamusumegp
com.krafton.dndm
com.kurogame.aki
com.kurogame.haru
com.kurogame.mingchao
com.kurogame.wutheringwaves.global
com.leiting.wf
com.levelinfinite.sgameGlobal
com.lilithgames.hgame.cn
com.lilithgames.solarland.android.cn
com.littleleogames.astreasixsidedoracles
com.longe.allstarhmt
com.madfingergames.legends
com.miHoYo.GenshinImpact
com.miHoYo.Nap
com.miHoYo.Yuanshen
com.miHoYo.bh3
com.miHoYo.enterprise.NGHSoD
com.miHoYo.hkrpg
com.miHoYo.ys
com.miHoYo.zenless
com.minidragon.idlefantasy
com.miniworldgame.creata.vn
com.miraclegames.farlight84
com.mobile.legends
com.modx.daluandou
com.mojang.minecraftpe
com.movtery.zalithlauncher
com.nanostudios.games.twenty.minutes
com.neowizgames.game.browndust2
com.netease.AVALON
com.netease.EVE
com.netease.aceracer
com.netease.allstar
com.netease.dfjs
com.netease.dunkcd
com.netease.dwrg
com.netease.eve.en
com.netease.g78na
com.netease.g93na
com.netease.h73hmt
com.netease.h75na
com.netease.hyxd
com.netease.idv
com.netease.jddsaef
com.netease.ko
com.netease.l22
com.netease.lglr
com.netease.ma84
com.netease.moba
com.netease.mrzh
com.netease.newspike
com.netease.nshm
com.netease.nshmhmt
com.netease.onmyoji
com.netease.party
com.netease.pes
com.netease.qrsj
com.netease.race
com.netease.sky
com.netease.soulofhunter
com.netease.tank
com.netease.tj
com.netease.tom
com.netease.wotb
com.netease.wyclx
com.netease.x19
com.netease.yhtj
com.netease.yyslscn
com.netease.yzs
com.nexon.bluearchive
com.nexon.kartdrift
com.nexon.mdnf
com.nexon.mod
com.nianticlabs.monsterhunter
com.nianticproject.ingress
com.oninou.FAPI
com.papegames.infinitynikki
com.pi.czrxdfirst
com.pinkcore.tkfm
com.playdigious.deadcells.mobile
com.playmini.miniworld
com.proxima.dfm
com.proximabeta.nikke
com.prpr.musedash
com.pubg
com.pubg.imobile
com.pubg.krmobile
com.pubg.newstate
com.pwrd.hotta.laohu
com.pwrd.huanta
com.pwrd.p5x
com.pwrd.persona5x.laohu
com.r2games.myhero.bilibili
com.rayark.cytus2
com.rayark.implosion
com.rekoo.pubgm
com.riotgames.league.teamfighttactics
com.riotgames.league.wildrift
com.roblox.client
com.rockstargames.rdr
com.savysoda.pss2.android
com.seasun.jx3
com.seasun.snowbreak.google
com.sega.ColorfulStage.en
com.sega.pjsekai
com.shangyoo.neon
com.shatteredpixel.shatteredpixeldungeon
com.shenlan.m.reverse1999
com.sofunny.Sausage
com.soulgamechst.majsoul
com.supercell.boombeach
com.supercell.clashroyale
com.supercell.moco
com.sy.dldlhsdj
com.t2ksports.nba2k20and
com.tencent.KiHan
com.tencent.hhw
com.tencent.ig
com.tencent.jkchess
com.tencent.letsgo
com.tencent.lolm
com.tencent.mf.uam
com.tencent.nba2kx
com.tencent.nfsonline
com.tencent.nikke
com.tencent.tmgp.WePop
com.tencent.tmgp.bh3
com.tencent.tmgp.cf
com.tencent.tmgp.cod
com.tencent.tmgp.codev
com.tencent.tmgp.dfjs
com.tencent.tmgp.dfm
com.tencent.tmgp.djsy
com.tencent.tmgp.dnf
com.tencent.tmgp.dwrg
com.tencent.tmgp.ffom
com.tencent.tmgp.gnyx
com.tencent.tmgp.kr.codm
com.tencent.tmgp.nz
com.tencent.tmgp.pubgmhd
com.tencent.tmgp.sgame
com.tencent.tmgp.speedmobile
com.tencent.tmgp.sskgame
com.tencent.tmgp.supercell.boombeach
com.tencent.tmgp.toaa
com.tencent.tmgp.wuxia
com.tencent.tmgp.yys.zqb
com.tencent.toaa
com.tgc.sky.android
com.the10tons.dysmantle
com.tipsworks.android.pascalswager
com.tipsworks.pascalswager
com.trampolinetales.lbal
com.tungsten.fcl
com.ubisoft.rainbowsixmobile.r6.fps.pvp.shooter
com.unity.mmd
com.valvesoftware.cswgsm
com.valvesoftware.source
com.vng.pubgmobile
com.xd.TLglobal
com.xd.dxlzz.taptap
com.xd.rotaeno.googleplay
com.xd.rotaeno.tapcn
com.xd.sce.promotion
com.xd.terraria
com.xd.xdt
com.xindong.torchlight
com.xjskp.tv.hnsc
com.yinhan.hunter
com.yongshi.tenojo
com.zlongame.mhmnz
com.ztgame.bob
com.ztgame.yyzy
com.zy.wqmt.cn
gplay.punishing.grayraven
jp.YoStarJP.BlueArchive
jp.YoStarJP.MajSoul
jp.co.bandainamcoent.BNEI0242
jp.co.craftegg.band
jp.co.cygames.princessconnectredive
jp.konami.masterduel
jp.konami.pesam
me.mugzone.emiria
me.tigerhix.cytoid
minitech.miniworld
moe.low.arc
net.kdt.pojavlaunch
net.wargaming.wot.blitz
org.flos.phira
org.maxbytes.lfs
sh.ppy.osulazer
supercell.brawlstars
supercell.clashofclans
supercell.squad
tw.sonet.allbw
tw.sonet.princessconnect
xd.sce.promotion
"

export PATH="${PATH}:/data/adb/magisk:/data/adb/ksu/bin:/data/adb/ap/bin"
export TZ="Asia/Shanghai"
if command -v busybox >/dev/null 2>&1; then
	grep() { busybox grep "$@"; }
	sed() { busybox sed "$@"; }
fi

function Remove_Asoul_package(){
local target_file="${1}"
[ -f "${target_file}" ] || return
local tmp_dir="/dev/tmp/Aloazny.$$"
mkdir -p "${tmp_dir}" || tmp_dir="/data/local/tmp/Aloazny.$$"; mkdir -p "${tmp_dir}"
local tmp_patterns="${tmp_dir}/patterns.$$"
local tmp_out="${tmp_dir}/out.$$"
echo "- 正在移除和Asoulopt冲突的游戏……"
echo "${Asoul_package}" | sed '/^[[:space:]]*$/d' > "${tmp_patterns}"
grep -v -F -f "${tmp_patterns}" "${target_file}" > "${tmp_out}"
[ -e "${tmp_out}" ] && cp -af "${tmp_out}" "${target_file}"
sed -i '/^#游戏$/,/^#游戏END$/{s/[[:space:]]*$//;/^#游戏$/b;/^#游戏END$/b;/^#.*/{N;/^[^\n]*\n$/d;};}' "${target_file}"
sed -i '/^#游戏$/,/^#游戏END$/{/^#游戏$/b;/^#游戏END$/b;:c;/^$/{N;/^\n$/{D;bc;};};}' "${target_file}"
sed -i '/^#游戏$/G' "${target_file}"
sed -i '/^#游戏$/,/^#游戏END$/{/^$/{N;/^\n$/D;}}' "${target_file}"
rm -rf "${tmp_dir}"
}
